name: ABM_Identifiability_python
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - matplotlib>=3.7.1
  - seaborn>=0.12.2
  - pandas>=2.0.2
  - numpy>=1.24.3
  - scipy>=1.10.1
  - numba>=0.57.0
  - polars>=0.18.4
  - pyarrow>=12.0.1
  - pip>=23.1.2
  - pip:
    - session_info>=1.0.0
