name: ABM_Identifiability_python
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - matplotlib==3.7.1
  - seaborn==0.12.2
  - pandas==2.0.2
  - numpy==1.24.3
  - xarray==2023.5.0
  -
